# Generated by Django 5.1.15 on 2026-09-20 21:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=180)),
                ('categoria', models.CharField(choices=[('alimentacion', 'Alimentación'), ('nomina', 'Nómina'), ('servicios', 'Servicios'), ('materiales', 'Materiales'), ('mantenimiento', 'Mantenimiento'), ('otro', 'Otro')], max_length=20, verbose_name='categoría')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('proveedor', models.CharField(blank=True, max_length=160)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='gastos/%Y/%m/')),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'gasto institucional',
                'verbose_name_plural': 'gastos institucionales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Guardería', max_length=140)),
                ('mision', models.TextField(default='Brindar cuidado, protección y educación integral en un ambiente seguro y afectuoso.')),
                ('vision', models.TextField(default='Ser una comunidad educativa referente en el desarrollo feliz de la primera infancia.')),
                ('direccion', models.CharField(blank=True, max_length=220)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institucion/')),
            ],
            options={
                'verbose_name': 'institución',
                'verbose_name_plural': 'institución',
            },
        ),
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellidos')),
                ('identificacion', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='identificación')),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.localdate)),
                ('grupo', models.CharField(blank=True, help_text='Ej.: Maternal, Inicial 1', max_length=80)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ninos/fotos/')),
                ('alergias', models.TextField(blank=True)),
                ('observaciones_medicas', models.TextField(blank=True)),
                ('representante', models.CharField(max_length=160)),
                ('parentesco', models.CharField(blank=True, max_length=50)),
                ('telefono_representante', models.CharField(max_length=30)),
                ('correo_representante', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=220)),
                ('pension_mensual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('graduado', 'Graduado')], default='activo', max_length=12)),
                ('token_familia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'niño/a',
                'verbose_name_plural': 'niños y niñas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('identificacion', models.CharField(max_length=30, unique=True, verbose_name='identificación')),
                ('cargo', models.CharField(default='Docente', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.localdate)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profesoras/fotos/')),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'profesora',
                'verbose_name_plural': 'profesoras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Use el primer día del mes')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=12)),
                ('observacion', models.CharField(blank=True, max_length=240, verbose_name='observación')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensualidades', to='core.nino', verbose_name='niño/a')),
            ],
            options={
                'verbose_name_plural': 'mensualidades',
                'ordering': ['-periodo', 'nino'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('tipo', models.CharField(choices=[('identidad', 'Identidad'), ('salud', 'Salud'), ('matricula', 'Matrícula'), ('contrato', 'Contrato'), ('certificado', 'Certificado'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('vence', models.DateField(blank=True, null=True)),
                ('subido', models.DateTimeField(auto_now_add=True)),
                ('carpeta', models.CharField(default='General', help_text='Ej.: Salud, Matrícula, Autorizaciones', max_length=100)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.nino', verbose_name='niño/a')),
            ],
            options={
                'verbose_name': 'documento del niño/a',
                'verbose_name_plural': 'documentos de niños y niñas',
                'ordering': ['-subido'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AporteFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=160)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('detalle', models.TextField(blank=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='aportes/%Y/%m/')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aportes', to='core.nino', verbose_name='niño/a')),
            ],
            options={
                'verbose_name': 'aporte familiar',
                'verbose_name_plural': 'aportes familiares',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NotaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('contenido', models.TextField()),
                ('color', models.CharField(choices=[('amarillo', 'Amarillo'), ('rosa', 'Rosa'), ('verde', 'Verde'), ('azul', 'Azul')], default='amarillo', max_length=10)),
                ('fijada', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nota personal',
                'verbose_name_plural': 'notas personales',
                'ordering': ['-fijada', '-actualizada'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoProfesora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('tipo', models.CharField(choices=[('identidad', 'Identidad'), ('salud', 'Salud'), ('matricula', 'Matrícula'), ('contrato', 'Contrato'), ('certificado', 'Certificado'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('vence', models.DateField(blank=True, null=True)),
                ('subido', models.DateTimeField(auto_now_add=True)),
                ('profesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.profesora')),
            ],
            options={
                'verbose_name': 'documento de profesora',
                'verbose_name_plural': 'documentos de profesoras',
                'ordering': ['-subido'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('mensaje', models.TextField(blank=True)),
                ('publicada', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('ninos', models.ManyToManyField(blank=True, help_text='Vacío = visible para todas las familias', related_name='publicaciones', to='core.nino')),
            ],
            options={
                'verbose_name': 'publicación para familias',
                'verbose_name_plural': 'comunicación con familias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='familias/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'webm', 'pdf'])])),
                ('descripcion', models.CharField(blank=True, max_length=180, verbose_name='descripción')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.publicacion', verbose_name='publicación')),
            ],
            options={
                'verbose_name': 'foto o video',
                'verbose_name_plural': 'fotos y videos',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Use el primer día del mes')),
                ('resumen', models.TextField()),
                ('logros', models.TextField(blank=True)),
                ('por_reforzar', models.TextField(blank=True)),
                ('observaciones_familia', models.TextField(blank=True)),
                ('publicado_familia', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='core.nino', verbose_name='niño/a')),
            ],
            options={
                'verbose_name': 'seguimiento mensual',
                'verbose_name_plural': 'avances y seguimiento',
                'ordering': ['-periodo', 'nino'],
            },
        ),
        migrations.CreateModel(
            name='HitoDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('motricidad', 'Motricidad'), ('lenguaje', 'Lenguaje'), ('social', 'Socioemocional'), ('cognitiva', 'Cognitiva'), ('autonomia', 'Autonomía')], max_length=20, verbose_name='área')),
                ('hito', models.CharField(max_length=200)),
                ('estrellas', models.PositiveSmallIntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], default=3)),
                ('nota', models.CharField(blank=True, max_length=240)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='core.seguimientomensual')),
            ],
            options={
                'verbose_name': 'hito de desarrollo',
                'verbose_name_plural': 'hitos de desarrollo',
                'ordering': ['area', 'hito'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='método')),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/%Y/%m/')),
                ('mensualidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='core.mensualidad')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'historial de pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='mensualidad',
            constraint=models.UniqueConstraint(fields=('nino', 'periodo'), name='mensualidad_unica_por_periodo'),
        ),
        migrations.AddConstraint(
            model_name='seguimientomensual',
            constraint=models.UniqueConstraint(fields=('nino', 'periodo'), name='seguimiento_unico_por_periodo'),
        ),
    ]
