# Generated by Django 5.1.15 on 2026-09-20 23:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profesora',
            name='ninos_asignados',
            field=models.ManyToManyField(blank=True, help_text='La profesora solo podrá registrar actividades de estos niños.', related_name='profesoras', to='core.nino', verbose_name='niños asignados'),
        ),
        migrations.AddField(
            model_name='profesora',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_profesora', to=settings.AUTH_USER_MODEL, verbose_name='usuario de acceso'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('area', models.CharField(choices=[('arte', 'Arte y creatividad'), ('motricidad', 'Motricidad'), ('lenguaje', 'Lenguaje'), ('cognitiva', 'Cognitiva'), ('social', 'Socioemocional'), ('autonomia', 'Autonomía'), ('juego', 'Juego libre'), ('otra', 'Otra')], max_length=20, verbose_name='área')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('observacion', models.TextField(blank=True, verbose_name='logros u observaciones')),
                ('compartir_familia', models.BooleanField(default=True, verbose_name='visible para la familia')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='core.nino', verbose_name='niño/a')),
                ('profesora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='core.profesora')),
            ],
            options={
                'verbose_name': 'actividad infantil',
                'verbose_name_plural': 'actividades infantiles',
                'ordering': ['-fecha', '-creada'],
                'permissions': (('view_all_actividad', 'Puede ver actividades de todas las profesoras'),),
            },
        ),
        migrations.CreateModel(
            name='FotoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='actividades/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=160, verbose_name='descripción')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.actividad')),
            ],
            options={
                'verbose_name': 'foto de actividad',
                'verbose_name_plural': 'fotos de actividades',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
