# Generated by Django 5.1.15 on 2026-09-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profesora_ninos_asignados_profesora_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(default='Kids Center', max_length=140),
        ),
    ]
