# Generated by Django 5.1.15 on 2026-10-03 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profesora_salario_mensual_nominadocente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_documento', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha del documento')),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=12)),
                ('nacionalidad', models.CharField(blank=True, default='Ecuatoriana', max_length=80)),
                ('representante_cedula', models.CharField(blank=True, max_length=30, verbose_name='cédula del representante')),
                ('padre_ocupacion', models.CharField(blank=True, max_length=120, verbose_name='ocupación del padre')),
                ('padre_lugar_trabajo', models.CharField(blank=True, max_length=160, verbose_name='lugar de trabajo del padre')),
                ('padre_telefono_laboral', models.CharField(blank=True, max_length=30, verbose_name='teléfono laboral del padre')),
                ('madre_ocupacion', models.CharField(blank=True, max_length=120, verbose_name='ocupación de la madre')),
                ('madre_lugar_trabajo', models.CharField(blank=True, max_length=160, verbose_name='lugar de trabajo de la madre')),
                ('madre_telefono_laboral', models.CharField(blank=True, max_length=30, verbose_name='teléfono laboral de la madre')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=160, verbose_name='nombre del contacto')),
                ('contacto_emergencia_parentesco', models.CharField(blank=True, max_length=60, verbose_name='parentesco del contacto')),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono del contacto')),
                ('tipo_sangre', models.CharField(blank=True, max_length=10, verbose_name='tipo de sangre')),
                ('enfermedad_cronica', models.BooleanField(default=False, verbose_name='¿tiene una enfermedad crónica?')),
                ('enfermedad_detalle', models.CharField(blank=True, max_length=240, verbose_name='detalle de la enfermedad')),
                ('toma_medicamentos', models.BooleanField(default=False, verbose_name='¿toma medicamentos?')),
                ('medicamentos_detalle', models.CharField(blank=True, max_length=240, verbose_name='medicamentos y dosis')),
                ('seguro_medico', models.BooleanField(default=False, verbose_name='¿tiene seguro médico?')),
                ('seguro_nombre', models.CharField(blank=True, max_length=120, verbose_name='nombre del seguro')),
                ('autoriza_imagen', models.BooleanField(default=True, verbose_name='autoriza el uso institucional de fotografías y videos')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('nino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_inscripcion', to='core.nino', verbose_name='niño/a')),
            ],
            options={
                'verbose_name': 'ficha de inscripción',
                'verbose_name_plural': 'fichas de inscripción',
            },
        ),
    ]
