# Generated by Django 5.1.15 on 2026-10-03 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fichainscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichainscripcion',
            name='archivo_firmado',
            field=models.FileField(blank=True, upload_to='documentos/fichas_firmadas/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='ficha firmada'),
        ),
    ]
